name: test

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://continuumio/miniconda3
    steps:
      - uses: actions/checkout@v2
      - name: page_test
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements/prod.txt
          pytest -v